# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6766727ca0ff62bb5d115ce6ffd4eaec7dbd02a65bcadd322dc9660b86575ef7bcc20bdb15f8b1cb32b0af0dfeb85e705ff41724c0ac4d3ed1b8c7bb5698fe7b

test:
  secret_key_base: f80a8f9f0d24d21e605395862d880d1370a70dce7011d6e709d0b9d3f9ec6371210bbee66eb582210cb5117941cfa9dde128cb848b842cf4e0a2aef229724cbe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
